In [1]:
import numpy as np

### 1. What is 2 to the power 5

In [2]:
pow(2,5)

32

### 2. Create a vector with following datapoints: 23,27,25,45,67

In [3]:
array1 = [23,25,27,45,67]
np.sort(array1)
vtr1 = np.array(array1)
print("We create vector from array 1:")
print(vtr1)

We create vector from array 1:
[23 25 27 45 67]


### 3. Assign names to the above data points in the vector relating to the day of the week with Mon,Tue,Wed,etc.

In [4]:
d = {'Monday': 23, 'Tuesday': 25, 'Wednesday': 27, 'Thursday': 45, 'Friday': 67}

### 4. What is the average(mean) of the values in vector formed in Q.2

In [5]:
np.mean(vtr1)

37.4

### 5. Find the day when the value was the higest.

In [6]:
d = {'Monday': 23, 'Tuesday': 25, 'Wednesday': 27, 'Thursday': 45, 'Friday': 67}
sorted(d.items(), key=lambda t: t[1])

[('Monday', 23),
 ('Tuesday', 25),
 ('Wednesday', 27),
 ('Thursday', 45),
 ('Friday', 67)]

In [7]:
new_value = max(d, key=d.get)
print("Highest value :",new_value)

Highest value : Friday


## Part B

### 1. Create a function that takes in a name as a string argument and returns a string of the form "Hello name"

In [8]:
def hello():
  name = str(input("Enter your name: "))
  if name:
    print ("Hello " + str(name))
  return 

hello()

Enter your name: Arjun
Hello Arjun


### 2. Create a function that accepts two arguments, an integer, and a vector of integers. It returns the count of the number of the occurrences of the integer in the input vector.

In [9]:
def countOccurrences(arr, n, x):
    res = 0
    for i in range(n):
        if x == arr[i]:
            res += 1
    return res

In [10]:
arr = [1, 2, 2, 2, 2, 3, 4, 7 ,8 ,8]
n = len(arr)
x = 4
print (countOccurrences(arr, n, x))

1


### 3. Create a function that accepts 3 integer values and returns their sum.However, if an integer value is evenly divisible by 3, then it does not count towards the sum.Return zero if all numbers are evenly divisible by 3.

In [11]:
def sum(a,b,c):
    return a+b+c

a= int(input("Enter first number:"))
if(a % 3 == 0):
    a=0

b= int(input("Enter second number:"))
if(b % 3 == 0):
    b=0

c= int(input("Enter third number:"))
if(c % 3 == 0):
    c=0
        
print("Sum of the given three numbers is: ", sum(a,b,c))

Enter first number:45
Enter second number:42
Enter third number:45
Sum of the given three numbers is:  0


### 4. Create a function that will return TRUE if an input integer is prime number. otherwise retuen false

In [12]:
n=int(input("Enter number: ")) 
k=0 
for i in range(2,n//2+1): 
    if(n%i==0): 
        k=k+1 
if(k<=0): 
    print("True") 
else: 
    print("False") 

Enter number: 44
False


## Part C

### 1. Create 2 vectors A and B,where A is (1,2,3) and B is (4,5,6).With these vectors,use the cbind() or rbind() function to create a 2 by 3 matrix from the vectors.

In [13]:
A = [1,2,3]
B = [4,5,6]
np.column_stack((A,B)).T

array([[1, 2, 3],
       [4, 5, 6]])

### 2. Create a 5 by 5 matrix consisting of the number 1-25 and assign it to the variable mat2. The top row should be the number 1-5.

In [14]:
import numpy as np
mat2 = np.arange(1,26).reshape(5,5)
print(mat2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


### Using indexing notation,grab a sub-sectoion of mat2 from the pervious excersie that looks like this:
[7,8]

[12,13]

In [15]:
mat2[1:3,1:3]

array([[ 7,  8],
       [12, 13]])

## Part D

In [16]:
import pydataset

In [17]:
pydataset.data()

dataset_id                                             title
0    AirPassengers       Monthly Airline Passenger Numbers 1949-1960
1          BJsales                 Sales Data with Leading Indicator
2              BOD                         Biochemical Oxygen Demand
3     Formaldehyde                     Determination of Formaldehyde
4     HairEyeColor         Hair and Eye Color of Statistics Students
..             ...                                               ...
752        VerbAgg                  Verbal Aggression item responses
753           cake                 Breakage Angle of Chocolate Cakes
754           cbpp                 Contagious bovine pleuropneumonia
755    grouseticks  Data on red grouse ticks from Elston et al. 2001
756     sleepstudy       Reaction times in a sleep deprivation study

[757 rows x 2 columns]

In [18]:
df=pydataset.data('mtcars')
df

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
Mazda RX4            21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
Mazda RX4 Wag        21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
Datsun 710           22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
Hornet 4 Drive       21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
Hornet Sportabout    18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   
Valiant              18.1    6  225.0  105  2.76  3.460  20.22   1   0     3   
Duster 360           14.3    8  360.0  245  3.21  3.570  15.84   0   0     3   
Merc 240D            24.4    4  146.7   62  3.69  3.190  20.00   1   0     4   
Merc 230             22.8    4  140.8   95  3.92  3.150  22.90   1   0     4   
Merc 280             19.2    6  167.6  123  3.92  3.440  18.30   1   0     4   
Merc 280C            17.8    6  167.6  123  3.92  3.440  18.90   1   0     4   
Merc 450SE           16.4    8  275.8  180  3.07  4.070  17.40   0   0     3   
Merc 450SL           17.3    8  275.8  180  3.07  3.730  17.60   0   0     3   
Merc 450SLC          15.2    8  275.8  180  3.07  3.780  18.00   0   0     3   
Cadillac Fleetwood   10.4    8  472.0  205  2.93  5.250  17.98   0   0     3   
Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3   
Chrysler Imperial    14.7    8  440.0  230  3.23  5.345  17.42   0   0     3   
Fiat 128             32.4    4   78.7   66  4.08  2.200  19.47   1   1     4   
Honda Civic          30.4    4   75.7   52  4.93  1.615  18.52   1   1     4   
Toyota Corolla       33.9    4   71.1   65  4.22  1.835  19.90   1   1     4   
Toyota Corona        21.5    4  120.1   97  3.70  2.465  20.01   1   0     3   
Dodge Challenger     15.5    8  318.0  150  2.76  3.520  16.87   0   0     3   
AMC Javelin          15.2    8  304.0  150  3.15  3.435  17.30   0   0     3   
Camaro Z28           13.3    8  350.0  245  3.73  3.840  15.41   0   0     3   
Pontiac Firebird     19.2    8  400.0  175  3.08  3.845  17.05   0   0     3   
Fiat X1-9            27.3    4   79.0   66  4.08  1.935  18.90   1   1     4   
Porsche 914-2        26.0    4  120.3   91  4.43  2.140  16.70   0   1     5   
Lotus Europa         30.4    4   95.1  113  3.77  1.513  16.90   1   1     5   
Ford Pantera L       15.8    8  351.0  264  4.22  3.170  14.50   0   1     5   
Ferrari Dino         19.7    6  145.0  175  3.62  2.770  15.50   0   1     5   
Maserati Bora        15.0    8  301.0  335  3.54  3.570  14.60   0   1     5   
Volvo 142E           21.4    4  121.0  109  4.11  2.780  18.60   1   1     4   

                     carb  
Mazda RX4               4  
Mazda RX4 Wag           4  
Datsun 710              1  
Hornet 4 Drive          1  
Hornet Sportabout       2  
Valiant                 1  
Duster 360              4  
Merc 240D               2  
Merc 230                2  
Merc 280                4  
Merc 280C               4  
Merc 450SE              3  
Merc 450SL              3  
Merc 450SLC             3  
Cadillac Fleetwood      4  
Lincoln Continental     4  
Chrysler Imperial       4  
Fiat 128                1  
Honda Civic             2  
Toyota Corolla          1  
Toyota Corona           1  
Dodge Challenger        2  
AMC Javelin             2  
Camaro Z28              4  
Pontiac Firebird        2  
Fiat X1-9               1  
Porsche 914-2           2  
Lotus Europa            2  
Ford Pantera L          4  
Ferrari Dino            6  
Maserati Bora           8  
Volvo 142E              2

### 1. Display the first 6 rows of df

In [19]:
df.head(6)

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
Mazda RX4          21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   
Valiant            18.1    6  225.0  105  2.76  3.460  20.22   1   0     3   

                   carb  
Mazda RX4             4  
Mazda RX4 Wag         4  
Datsun 710            1  
Hornet 4 Drive        1  
Hornet Sportabout     2  
Valiant               1

### 2. What is the average mpg value for all the cars?

In [20]:
df['mpg'].mean()

20.090624999999996

### 3. Select the rows where all the cars have 6 cylinders (cyl column)

In [21]:
df1 = df.loc[df['cyl'] == 6]
df1

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4       21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
Valiant         18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
Merc 280        19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
Merc 280C       17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
Ferrari Dino    19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6

### 4. Select the column am,gear, and carb.

In [22]:
df2 = df[['am', 'gear','carb']]
df2

am  gear  carb
Mazda RX4             1     4     4
Mazda RX4 Wag         1     4     4
Datsun 710            1     4     1
Hornet 4 Drive        0     3     1
Hornet Sportabout     0     3     2
Valiant               0     3     1
Duster 360            0     3     4
Merc 240D             0     4     2
Merc 230              0     4     2
Merc 280              0     4     4
Merc 280C             0     4     4
Merc 450SE            0     3     3
Merc 450SL            0     3     3
Merc 450SLC           0     3     3
Cadillac Fleetwood    0     3     4
Lincoln Continental   0     3     4
Chrysler Imperial     0     3     4
Fiat 128              1     4     1
Honda Civic           1     4     2
Toyota Corolla        1     4     1
Toyota Corona         0     3     1
Dodge Challenger      0     3     2
AMC Javelin           0     3     2
Camaro Z28            0     3     4
Pontiac Firebird      0     3     2
Fiat X1-9             1     4     1
Porsche 914-2         1     5     2
Lotus Europa          1     5     2
Ford Pantera L        1     5     4
Ferrari Dino          1     5     6
Maserati Bora         1     5     8
Volvo 142E            1     4     2

### 5. Create a new column called performance, which is calculated by hp/wt.

In [23]:
df["Performance"] = df["hp"]/df["wt"]
df

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
Mazda RX4            21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
Mazda RX4 Wag        21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
Datsun 710           22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
Hornet 4 Drive       21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
Hornet Sportabout    18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   
Valiant              18.1    6  225.0  105  2.76  3.460  20.22   1   0     3   
Duster 360           14.3    8  360.0  245  3.21  3.570  15.84   0   0     3   
Merc 240D            24.4    4  146.7   62  3.69  3.190  20.00   1   0     4   
Merc 230             22.8    4  140.8   95  3.92  3.150  22.90   1   0     4   
Merc 280             19.2    6  167.6  123  3.92  3.440  18.30   1   0     4   
Merc 280C            17.8    6  167.6  123  3.92  3.440  18.90   1   0     4   
Merc 450SE           16.4    8  275.8  180  3.07  4.070  17.40   0   0     3   
Merc 450SL           17.3    8  275.8  180  3.07  3.730  17.60   0   0     3   
Merc 450SLC          15.2    8  275.8  180  3.07  3.780  18.00   0   0     3   
Cadillac Fleetwood   10.4    8  472.0  205  2.93  5.250  17.98   0   0     3   
Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3   
Chrysler Imperial    14.7    8  440.0  230  3.23  5.345  17.42   0   0     3   
Fiat 128             32.4    4   78.7   66  4.08  2.200  19.47   1   1     4   
Honda Civic          30.4    4   75.7   52  4.93  1.615  18.52   1   1     4   
Toyota Corolla       33.9    4   71.1   65  4.22  1.835  19.90   1   1     4   
Toyota Corona        21.5    4  120.1   97  3.70  2.465  20.01   1   0     3   
Dodge Challenger     15.5    8  318.0  150  2.76  3.520  16.87   0   0     3   
AMC Javelin          15.2    8  304.0  150  3.15  3.435  17.30   0   0     3   
Camaro Z28           13.3    8  350.0  245  3.73  3.840  15.41   0   0     3   
Pontiac Firebird     19.2    8  400.0  175  3.08  3.845  17.05   0   0     3   
Fiat X1-9            27.3    4   79.0   66  4.08  1.935  18.90   1   1     4   
Porsche 914-2        26.0    4  120.3   91  4.43  2.140  16.70   0   1     5   
Lotus Europa         30.4    4   95.1  113  3.77  1.513  16.90   1   1     5   
Ford Pantera L       15.8    8  351.0  264  4.22  3.170  14.50   0   1     5   
Ferrari Dino         19.7    6  145.0  175  3.62  2.770  15.50   0   1     5   
Maserati Bora        15.0    8  301.0  335  3.54  3.570  14.60   0   1     5   
Volvo 142E           21.4    4  121.0  109  4.11  2.780  18.60   1   1     4   

                     carb  Performance  
Mazda RX4               4    41.984733  
Mazda RX4 Wag           4    38.260870  
Datsun 710              1    40.086207  
Hornet 4 Drive          1    34.214619  
Hornet Sportabout       2    50.872093  
Valiant                 1    30.346821  
Duster 360              4    68.627451  
Merc 240D               2    19.435737  
Merc 230                2    30.158730  
Merc 280                4    35.755814  
Merc 280C               4    35.755814  
Merc 450SE              3    44.226044  
Merc 450SL              3    48.257373  
Merc 450SLC             3    47.619048  
Cadillac Fleetwood      4    39.047619  
Lincoln Continental     4    39.638643  
Chrysler Imperial       4    43.030870  
Fiat 128                1    30.000000  
Honda Civic             2    32.198142  
Toyota Corolla          1    35.422343  
Toyota Corona           1    39.350913  
Dodge Challenger        2    42.613636  
AMC Javelin             2    43.668122  
Camaro Z28              4    63.802083  
Pontiac Firebird        2    45.513654  
Fiat X1-9               1    34.108527  
Porsche 914-2           2    42.523364  
Lotus Europa            2    74.686054  
Ford Pantera L          4    83.280757  
Ferrari Dino            6    63.176895  
Maserati Bora           8    93.837535  
Volvo 142E              2    39.208633

### 6. What is the mpg of the Hornet Sportabout?

In [24]:
df.loc[["Hornet Sportabout"],["mpg"]]

mpg
Hornet Sportabout  18.7